name: Build x86 Image

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'

jobs:
  build:
    name: Build x86
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/go-build
          key: ${{ runner.os }}-go-x86-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-x86-build-

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Unit test
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          make ut

      - name: Build
        run: |
          go get -u github.com/securego/gosec/cmd/gosec
          make release
          make tar

      - name: Upload image to artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: image.tar

  single-e2e:
    needs: build
    name: 1-master-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Init Kind
        run: |
          pip install j2cli --user
          pip install "j2cli[yaml]" --user
          sudo PATH=~/.local/bin:$PATH make kind-init

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Install Kube-OVN
        run: |
          docker load --input image.tar
          sudo make kind-install

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Run E2E
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          sudo kubectl cluster-info
          sudo chmod 666 /home/runner/.kube/config
          make e2e

  ha-e2e:
    needs: build
    name: 3-master-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Init Kind
        run: |
          pip install j2cli --user
          pip install "j2cli[yaml]" --user
          sudo PATH=~/.local/bin:$PATH make kind-init-ha

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Install Kube-OVN
        run: |
          docker load --input image.tar
          sudo make kind-install

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Run E2E
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          sudo kubectl cluster-info
          sudo chmod 666 /home/runner/.kube/config
          make e2e


  ipv6-e2e:
    needs: build
    name: ipv6-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Init Kind
        run: |
          pip install j2cli --user
          pip install "j2cli[yaml]" --user
          sudo PATH=~/.local/bin:$PATH make kind-init-ipv6

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Load Image
        run: |
          docker load --input image.tar

      - name: Install Kube-OVN
        run: |
          docker load --input image.tar
          sudo make kind-install-ipv6

  push:
    needs: [single-e2e, ha-e2e, ipv6-e2e]
    name: push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Load Image
        run: |
          docker load --input image.tar

      - name: Security Scan
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          make scan


      - name: Push
        if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag kubeovn/kube-ovn:$TAG pastens/kube-ovn:$TAG-amd64
          docker tag kubeovn/kube-ovn:$TAG pastens/kube-ovn:$COMMIT-amd64
          docker images
          docker push pastens/kube-ovn:$TAG-amd64
          docker push pastens/kube-ovn:$COMMIT-amd64
          docker manifest create pastens/kube-ovn:$TAG --amend pastens/kube-ovn:$TAG-amd64
          docker manifest create pastens/kube-ovn:$COMMIT --amend pastens/kube-ovn:$COMMIT-amd64
          docker manifest push pastens/kube-ovn:$TAG
          docker manifest push pastens/kube-ovn:$COMMIT
