name: Build arm64 Image
on:
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0
      - name: Build
        run: |
          go get -u github.com/securego/gosec/cmd/gosec
          make release-arm
      - name: Push
        if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          TAG=$(cat VERSION)
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag kubeovn/kube-ovn:$TAG pastens/kube-ovn:$TAG-arm64
          docker tag kubeovn/kube-ovn:$TAG pastens/kube-ovn:$COMMIT-arm64
          docker images
          docker push pastens/kube-ovn:$TAG-arm64
          docker push pastens/kube-ovn:$COMMIT-arm64
          docker manifest create pastens/kube-ovn:$TAG --amend pastens/kube-ovn:$TAG-arm64 --amend pastens/kube-ovn:$TAG-amd64
          docker manifest create pastens/kube-ovn:$COMMIT --amend pastens/kube-ovn:$COMMIT-arm64 --amend pastens/kube-ovn:$COMMIT-amd64
          docker manifest push pastens/kube-ovn:$TAG
          docker manifest push pastens/kube-ovn:$COMMIT
