name: Build x86 Image

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0

      - name: Unit test
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          make ut

      - name: Build
        run: |
          go get -u github.com/securego/gosec/cmd/gosec
          make release

      - name: Security Scan
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          make scan

      - name: Init Kind
        run: |
          sudo make kind-init

      - name: Run E2E
        run: |
          sudo kubectl cluster-info
          sudo chmod 666 /home/runner/.kube/config
          make e2e

      - name: Push
        if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag kubeovn/kube-ovn:$TAG kubeovn/kube-ovn:$COMMIT
          docker images
          docker push kubeovn/kube-ovn:$TAG
          docker push kubeovn/kube-ovn:$COMMIT
